[workspace]
resolver = "2"
members = [
    "api",
    "frontend-builder"
]

[workspace.dependencies]
uuid = { version = "1.3.4", features = ["v4", "fast-rng", "macro-diagnostics", "serde"] }
thiserror = "2.0.16"